{% set name = "omegaconf" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/omry/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0168f962822b7059c7553c4346541596ea48c0b542628d41a348a12eeaf971ff

build:
  number: 0
  skip: true  # [py2k and py==34 and py==35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - pytest-runner
    - antlr =4.8
  run:
    - python
    - pyyaml
    - antlr-python-runtime =4.8
    - dataclasses  # [py==36]
    - typing_extensions

test:
  imports:
    - omegaconf
  requires:
    - pytest
    - pytest-benchmark
    - pytest-mock
    - pytest-lazy-fixture
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/omry/omegaconf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Flexible python configuration system

  description: |
    OmegaConf is a hierarchical configuration system, with support for merging
    configurations from multiple sources (YAML config files,
    dataclasses/objects and CLI arguments) providing a consistent API
    regardless of how the configuration was created.
  doc_url: https://omegaconf.readthedocs.io/
  dev_url: https://github.com/omry/omegaconf

extra:
  recipe-maintainers:
    - mdraw
    - omry
