{% set name = "omegaconf" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/omry/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9586b6623d4abf514979612f987261971a58da2dc7a9224bebd017848c9ad80a


build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # Minor version must match between antlr and antlr-python-runtime
    # https://github.com/omry/omegaconf/issues/798
    - antlr 4.9
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - antlr-python-runtime 4.9
    - typing_extensions

test:
  imports:
    - omegaconf
  requires:
    - pytest
    - pytest-benchmark
    - pytest-mock
    - pytest-lazy-fixture
    - pip
  source_files:
    - tests
  commands:
    - pip check
    - pytest --ignore tests/test_pydev_resolver_plugin.py --ignore tests\structured_conf\test_structured_config.py --ignore tests\test_utils.py

about:
  home: https://github.com/omry/omegaconf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Flexible python configuration system

  description: |
    OmegaConf is a hierarchical configuration system, with support for merging
    configurations from multiple sources (YAML config files,
    dataclasses/objects and CLI arguments) providing a consistent API
    regardless of how the configuration was created.
  doc_url: https://omegaconf.readthedocs.io/
  dev_url: https://github.com/omry/omegaconf

extra:
  recipe-maintainers:
    - maresb
    - mdraw
    - omry
    - benjaminrwilson
