{% set name = "omegaconf" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/omry/{{ name|lower }}/archive/{{ version }}.tar.gz
  sha256: ce7bc44840c7bbe3c575a6095db98446d9f7686196bf606b46b532531448a296

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - pyyaml
    - six

test:
  imports:
    - omegaconf
  requires:
    - pytest
  source_files:
    - tests
    - pytest.ini
  commands:
    - pytest tests

about:
  home: https://github.com/omry/omegaconf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Flexible python configuration system

  description: |
    OmegaConf is a hierarchical configuration system, with support for merging
    configurations from multiple sources (YAML config files,
    dataclasses/objects and CLI arguments) providing a consistent API
    regardless of how the configuration was created.
  doc_url: https://omegaconf.readthedocs.io/
  dev_url: https://github.com/omry/omegaconf

extra:
  recipe-maintainers:
    - mdraw
