{% set name = "omegaconf" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/omegaconf-{{ version }}.tar.gz
  sha256: 59ff9fba864ffbb5fb710b64e8a9ba37c68fa339a2e2bb4f1b648d6901552523

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - antlr 4.9
  run:
    - python >=3.7,<3.11
    - pyyaml
    - antlr-python-runtime 4.9
    - typing_extensions

test:
  imports:
    - omegaconf
  requires:
    - pytest
    - pytest-benchmark
    - pytest-mock
    - pytest-lazy-fixture
    - pip
    # Temporary pin <https://github.com/conda-forge/omegaconf-feedstock/pull/40#issuecomment-1294669062>
  source_files:
    - tests
  commands:
    - pip check
    - pytest --ignore tests/test_pydev_resolver_plugin.py --ignore tests\structured_conf\test_structured_config.py --ignore tests\test_utils.py

about:
  home: https://github.com/omry/omegaconf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Flexible python configuration system

  description: |
    OmegaConf is a hierarchical configuration system, with support for merging
    configurations from multiple sources (YAML config files,
    dataclasses/objects and CLI arguments) providing a consistent API
    regardless of how the configuration was created.
  doc_url: https://omegaconf.readthedocs.io/
  dev_url: https://github.com/omry/omegaconf

extra:
  recipe-maintainers:
    - maresb
    - mdraw
    - omry
    - benjaminrwilson
